name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy-via-sftp:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.1
      with:
        username: root
        server: 85.214.250.162
        port: 22
        ssh_private_key: ${{ secrets.SECRET_VPS }}
        
        local_path: ./*
        
        remote_path: /var/www/vhosts/uacode.tk/httpdocs
        
        args: '-o ConnectTimeout=5'
